import * as bitcoinUtil from './bitcoin';
import * as tss from './tss';

export * as walletUtil from './walletUtil';
export * from './baseCoin';
export { signMessage, verifyMessage } from '@bitgo/sdk-keys';
export * from './bitcoin';
export * from './bitgoBase';
export * from './config';
export * from './coinFactory';
export * from './defi';
export { getSharedSecret, signMessageWithDerivedEcdhKey, verifyEcdhSignature } from '@bitgo/sdk-keys';
export * from './enterprise';
export * from './environments';
export * from './errors';
export * from './inscriptionBuilder';
export * from './internal';
export * from './keychain';
export * as bitcoin from './legacyBitcoin';
export * from './market';
export * from './pendingApproval';
export { WalletProofs } from './proofs';
export * from './recovery';
export * from './staking';
export * from './trading';
export * from './tss';
export { sendSignatureShare } from './tss';
export * from './types';
export * from './utils';
export * from './safe';
export * from './wallet';
export * from './webauthn';
export * from './webhook';
export { bitcoinUtil };
export { tss };
