// MPC/TSS primitives moved to @bitgo/sdk-keys. Re-exported here so existing imports keep working.
export {
  BIP32,
  bigIntFromBufferBE,
  bigIntFromBufferLE,
  bigIntFromU8ABE,
  bigIntToBufferBE,
  bigIntToBufferLE,
  clamp,
  combineRound4DklsDsgMessages,
  Ecdsa,
  ECDSA,
  Ed25519BIP32,
  Ed25519Curve,
  Eddsa,
  EDDSA,
  getPaillierPublicKey,
  HDTree,
  KeyShare,
  rangeProof,
  Secp256k1Curve,
  ShamirSecret,
} from '@bitgo/sdk-keys';
